### ISSUE TITLE
Windows 11 JavaScript error at launch

### ISSUE THREAD

**Issue by ptmks15** [donn/nudelta#10]
When I try to run the new windows build it throws a JavaScript error (attached below). My Java and Windows 11 install are all up to date, not sure what the issue is. ![Screenshot_20221225_075600](https://user-images.githubusercontent.com/80654097/209499290-edf9b2a3-ac1d-434c-910d-2144d1456402.png)

**Comment by donn** [comment]
Weird... I'm guessing I missed something in the build steps for Windows.

Is anyone else experiencing this?

**Comment by Karnbir** [comment]
Same issue here (Windows 11): 
![image](https://user-images.githubusercontent.com/69281441/209602401-b2badfa8-9903-41c5-89ab-af3e1fbefd07.png)

**Comment by N0fix** [comment]
Had this bug before windows release changes. 
Please provide compilation steps you made.

**Comment by donn** [comment]
@N0fix I believe they're just using the build from the CI: https://github.com/donn/nudelta/blob/fc719d96fdc5f84194a266851f783d83d7294678/.github/workflows/ci.yml#L25

**Comment by lime517** [comment]
Same issue here, just using the compiled .6.0 .exe release.

**Comment by donn** [comment]
![image](https://user-images.githubusercontent.com/12652988/210135559-c2dea674-baef-47ff-b7f4-cc6ab392dce4.png)

Well- I've reproduced the issue on my end on a fresh Windows 11 VM. Which is... lovely, because that error still provides nothing of value.

**Comment by donn** [comment]
Found the issue: A bug with `cmake-js` v7.0.0. I updated `cmake-js`. https://github.com/cmake-js/cmake-js/pull/289

**Comment by donn** [comment]
Just merged- please try the [latest release](https://github.com/donn/nudelta/releases/latest). Sorry for the wait!
