### ISSUE TITLE
Halo75 - remap is written but not applied nor saved

### ISSUE THREAD

**Issue by pngo** [donn/nudelta#19]
Remaps are said to be written 
![image](https://user-images.githubusercontent.com/549984/210221064-3434bb00-49e5-4f04-baa1-a30c53b579d9.png)

Typing in Notepad, the mapping is not applied.

Closing nudelta, opening nudelta again,  and reloading keyboard, the default keymap is shown. (proving the keymap has not been written)

Nudelta version : 0.6.3
OS: Win 10
Keyboard: Halo75
Firmware:  0102

**Comment by donn** [comment]
Nudelta does not read the incoming keymap from your keyboard, so reloading it will always show the default keymap.

Out of curiosity- can you try switching your keyboard to Mac mode and seeing if it remapped that one?

**Comment by pngo** [comment]
Switched to Mac mode, and the keymap works. So yes it was writing the keymap to the Mac Mode, even though it detected Windows correctly at start up of nudelta (refer back to screenshot in first post)

**Comment by nocturne1** [comment]
Can confirm this behavior. We're almost there!

**Comment by donn** [comment]
…I'm confused now. I flipped it in the first place because @nocturne1 reported this same behavior on 0.6.2.

Can you both try 0.6.2? Literally the only change from 0.6.3 is that the Mac and Windows mode are swapped around. That's it: https://github.com/donn/nudelta/releases/tag/0.6.2

**Comment by nocturne1** [comment]
No confusion here with the physical switch.

- 0.6.2 physical switch in M mode, software in Mac mode. Would program right command key to right-control, and then left command key would change to windows mode (forgot what key it went to).  Could only get command key back by moving switch to W.

- 0.6.3 physical switch in M mode, software in Mac mode. Would program right command key, and then nothing would change. Moved physical switch to W mode, then I saw that the right command key would be right-control, and other keys were still windows.

**Comment by pngo** [comment]
Difference in Windows / Mac builds then ?

**Comment by donn** [comment]
The builds are identical.

From what I'm seeing here- it appears that reverting the codebase to the state of 0.6.2 but also switching the YAML files around is probably the right approach. I'll try that when I have some time.

**Comment by Weathercold** [comment]
So the problem was that the yaml files are reversed? I tried to inform you about this a week ago but I think you didn't see it 😅 https://github.com/donn/nudelta/commit/99c38728427f1031544d0673e4b764213535ed2f#r94643080

**Comment by donn** [comment]
@Weathercold You're right!! I didn't! I scrolled all the way down, didn't see anything and I was like "weird, is it a glitched notification?"

Thanks for the alert, this is simpler than I expected lol

**Comment by donn** [comment]
Try 0.6.4. Sorry this is taking so long…

**Comment by pngo** [comment]
Can confirm it works now as expected! Thank you and ill be happy to test in future as well.

**Comment by nocturne1** [comment]
Can also confirm this fixed things. Thanks @donn !
