### ISSUE TITLE
Remapping a key combination

### ISSUE THREAD

**Issue by tapir** [donn/nudelta#22]
Is it possible to remap "Win" + "Left" combination to "Home"?

**Comment by donn** [comment]
Sadly no. The two supported keyboards do not support layers as we traditionally understand them: just a limited Fn layer for the keys we already know have an Fn-functionality, such as 1, 2, 3, 4, Up, Down, Left and Right, and of course, the F-keys.

You can use AutoHotkey (Windows), Karabiner Elements (Mac) or Input-Remapper (Linux) to handle this at the OS-level.
