### ISSUE TITLE
What permissions do I need to enable

### ISSUE THREAD

**Issue by kieron** [donn/nudelta#23]
Hello, I am using on mac and getting this error:

![image](https://user-images.githubusercontent.com/8655212/213209317-1242efab-65df-4f0e-be64-c02b6f8c1425.png)

But can't see what permissions I need to apply.

Thanks

**Comment by donn** [comment]
Hello, Kieron: Input Monitoring permissions. Sorry about that- this particular message is common across Windows, macOS and Linux, so I can't be super specific here.

**Comment by kieron** [comment]
Great thanks. Quick side question- how can I achieve one click f3/f4 to do their native mac functions? eg f8 is easy because playpause is on the list, but how could I map f3 to mission control for example?

thanks @donn !

**Comment by donn** [comment]
@kieron In macOS, they're to simply be assigned "F3" and "F4". Their behavior depends on this:

![image](https://user-images.githubusercontent.com/12652988/215548780-8b96345f-e59e-47a9-a9cb-524301349620.png)

If it's not checked, F3/F4 do Mission Control/Launchpad. If it's checked, Fn+F3 and Fn+F4 do them instead.

**Comment by czottmann** [comment]
Heads-up, @donn: I noticed that on Mac I get that very error when [Karabiner-Elements](https://karabiner-elements.pqrs.org/) is running. Once the Karabiner app & daemon are no longer running, nudelta can write to the Air75 no problem.

So: quit Karabiner entirely, run nudelta, restart Karabiner afterwards.
