### ISSUE TITLE
incompatible architecture

### ISSUE THREAD

**Issue by shachardevops** [donn/nudelta#27]
How can i rebuild the macos app? i am getting this error
```
(mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

**Comment by donn** [comment]
We've resolved this privately: but just use a pre-built version under Rosetta:

https://support.apple.com/en-eg/HT211861

I don't have access to an M1 Mac, so I can't do much about build instructions. Sorry.
