### ISSUE TITLE
"Search" key not working?

### ISSUE THREAD

**Issue by taitix** [donn/nudelta#32]
Great software!!!

I tried assigning "search" key from GUI,
but not working on Windows/Android.

"search" key works with my niz 82 keyboard on both Windows and Android.

**Comment by donn** [comment]
I don't think the search key works on the Air75, period. Sorry about that.

If it's Halo75, sadly debugging is difficult because I do not actually have one. If any community members would be willing to check, I'd appreciate it.

**Comment by donn** [comment]
Liner from the NuPhy discord just checked and the key straight up does not work on Windows. It's a Mac key apparently.
