### ISSUE TITLE
Remapping `del` not working

### ISSUE THREAD

**Issue by timephy** [donn/nudelta#33]
Hey,
first of all - thanks for making this!
Nuphy's Console is a piece of ****, i was so frustrated about it before finding this... So thanks again and good job!

# Bug?
I wanted to report a (supposed) bug:
I was not able to **remap my (top-right) `del` key to anything else** - even after a "Write successful" it still functions as a `del` key.

When rebinding the button below (`pgup`) to `del`, this works without a problem. So only remapping `del` to anything else seems to not be functional.

## Not related suggestion
I respect your wish to not implement LED controlling functionality  as I do not wish to use the LEDs either... But it would be nice to have a function to simply "deactivate all LEDs" :)
(Except for battery indicator and status)

**Comment by donn** [comment]
`Del` key bug fixed on Air75.

I actually do use the LEDs, it's just that the default modes are perfectly adequate for me. If you want to turn them off, `Fn + Down Arrow` a couple times will turn the backlight off and `Fn + / + Down Arrow` will turn the sidelights off.
