### ISSUE TITLE
Allow for remapping of the default fn key

### ISSUE THREAD

**Issue by Esaron** [donn/nudelta#39]
Neither nuphy console nor nudelta seem to allow remapping of this key. Is there a physical limitation of some kind?

**Comment by donn** [comment]
No- it's just that it also remaps every single shortcut using the Fn key, including the factory reset shortcut. i.e.- if something messes up, you'd have to reinstall the firmware from scratch to fix it.

Nudelta actually allows you to remap the Fn key- just click on it in the UI 5 times in a row and you'll receive a warning that will unlock Fn key remapping at your own risk.
