### ISSUE TITLE
Air 75 - No supported keyboard found

### ISSUE THREAD

**Issue by vartimaios** [donn/nudelta#44]
Hi,

I know it was asked before but it was said that it got fixed on a previous version. I am trying to configure my Air 75 on my mac but I get the error message "No supported keyboard found. Make sure it's plugged in via USB, then File > Reload Keyboard to retry.".

Does anyone know how I could solve it?

Thanks in advance!

**Comment by donn** [comment]
Hiya- couple of questions:

* Which version of macOS are you using?
* Have you given input monitoring permissions to Nudelta? It's a bit iffy about requesting them at the moment, sorry about that.

**Comment by nocturne1** [comment]
I have the same issue with my Halo75 after upgrading to Ventura 13.3.  It won't even prompt for the input monitoring if it was deleted, and still doesn't work if manually added back. It certainly seems as if Apple changed something.

**Comment by vartimaios** [comment]
> Hiya- couple of questions:
> 
> * Which version of macOS are you using?
> * Have you given input monitoring permissions to Nudelta? It's a bit iffy about requesting them at the moment, sorry about that.

Hello,

-  I have Ventura 13.3 on an intel model.
-  I have given input monitoring permissions to Nudelta.

**Comment by nocturne1** [comment]
Issue continues for me on Ventura 13.3.1.

**Comment by maciejkorsan** [comment]
same here

**Comment by donn** [comment]
Finally got around to updating my Mac- confirmed. Going to try to see what's wrong with the darn thing.

**Comment by donn** [comment]
Latest release now live at https://github.com/donn/nudelta/releases/tag/0.7.0.
