### ISSUE TITLE
HID error writing to keyboard "Invalid function"

### ISSUE THREAD

**Issue by jacostro** [donn/nudelta#50]
### Version

0.7.1

### Operating System

Windows 10.0.19045.2846 (22H2)

### Description

Keyboard: Air75
Firmware: 0124

Hi

Attempt to write any changes to keyboard results with a dialog:
```
Failed to write to keyboard: HidD_SetFeature: (0x00000001) Invalid function
```
It works with version 0.7.0.

**Comment by donn** [comment]
Should be fixed now.
