### ISSUE TITLE
Unsupported Keyboard Error for air96

### ISSUE THREAD

**Issue by arthurlacoste** [donn/nudelta#55]
### Version

0.7.3

### Operating System

MacBook Pro 14' 2023
Puce Apple M2 Max
ram 64 Go
macOS 13.4.1 (22F82)

### Description

Hello,
first of all - This s a really cool project!

I encountered an issue with my Air96 when attempting to use it. Upon plugging it in, I received the following error message:

"No supported keyboards found, but a similar keyboard, 'BY Tech NuPhy Air96', has been found. If you believe this keyboard not being supported is an error, please file a bug report."

It seems that the system recognizes a similar keyboard, but not the exact model I own. 

Steps to Reproduce:

Plug in Air96 to the computer.
Observe the error message: "No supported keyboards found, but a similar keyboard, 'BY Tech NuPhy Air96', has been found."

Actual Behavior:
The system does not recognize the keyboard and displays an error message suggesting a similar but different keyboard.

Thank you for your attention

**Comment by donn** [comment]
Hi- the similar keyboard in question is the Air75. Nudelta only supports the Air75 and Halo75. Support for Air96 is on hold unfortunately- I'm super busy.

We're tracking it in #40.
