### ISSUE TITLE
Semicolon and Quote are backwards

### ISSUE THREAD

**Issue by bgiesing** [donn/nudelta#61]
### Version

0.7.3

### Operating System

Version 22H2 (OS Build 23526.1000)

### Description

I was trying get the Colemak-DH CAW Wide layout into my Air75 directly which has the semicolon where the Left Bracket normally is and Quote where the Right Bracket is. Setting it like that in Nudelta produces the opposite result, hitting the Left Bracket key types Quote and Right Bracket does Semicolon. I had to reverse it manually to get it to work properly

**Comment by donn** [comment]
Slightly off- the indices for the bracket keys are reversed, not the values for the colon and comma. But confirmed. Working on it
