### ISSUE TITLE
Failed to write configuration after grant Input Monitoring permissions in System Preferences

### ISSUE THREAD

**Issue by lyc2345** [donn/nudelta#65]
### Version

0.7.4

### Operating System

macOS: Ventura 13.4.1
chip: Apple M2

<img width="392" alt="Screenshot 2023-10-27 at 13 57 35" src="https://github.com/donn/nudelta/assets/10074699/0e393385-3429-47dd-abd0-faf5a42d79c1">

<img width="1102" alt="Screenshot 2023-10-27 at 13 58 15" src="https://github.com/donn/nudelta/assets/10074699/0c9c5018-e394-4958-84ea-9feacadc6624">

### Description

I already gave Input Monitoring permission but kept receiving this error popup. No matter how many times I killed the app and permission in System Preferences, then  reinstalled, gave permission but still failed.

**Comment by donn** [comment]
This appears to be a problem on Apple Silicon versions of macOS: I don't have an immediate fix for it as I do not own an Apple Silicon Mac. https://github.com/donn/nudelta/issues/37
