### ISSUE TITLE
F key and Fn

### ISSUE THREAD

**Issue by ddiazescandon** [donn/nudelta#7]
Hi, Im aware that probably this is not an issue from your side.

I've trying to set up a Mac setting that work on windows too.  But for some odd reason I notice that every single F key is pressing a Fn key for a second, and even when it is set to do F1 in both F1 and F1 +Fn it is always triggering F1+Fn, and this is the default configuration.

**Comment by donn** [comment]
Short version: `Fn + Tab + R` on your keyboard should restore the expected behavior.

Long version:

![image](https://user-images.githubusercontent.com/12652988/204227742-48faad2a-f909-4450-9d22-d254b281c886.png)

**Comment by ddiazescandon** [comment]
It is confusing. I didn't want to rely on the window switch. I move constantly from Mac to windows and I was used to use a single keyboard without touching anything (Logi mx) and the fn key was usable in window and Mac (same combinations). But I get it. BTW thank you very much for this useful map and the keyboard mapping it is extremely helpful

**Comment by donn** [comment]
@ddiazescandon Cheers! Yeah, much as I love this keyboard- a lot of it makes me scratch my head a bit.
